language: python

sudo: required

python:
    - "2.7"
    - "3.4"
    - "3.5"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libdmtx0a

install: pip install tox-travis

script: tox
